# only the blender internal python interpreter is required

os: windows

# safelist
branches:
  only:
  - main

# Define which python version to build against.
# As blender comes bundled with it's own python you can use just one version if you like
python:
  - "3.10"

install:
  # create temp directory where we store a recent blender version
  - mkdir tmp
  - cd tmp

  # download the blender version you want to test against
  - wget https://download.blender.org/release/Blender3.3/blender-3.3.0-windows-x64.zip

  # Extract the archive
  - tar -xf blender-3.3.0-windows-x64.zip

  # test launch blender (background)
  - cd blender-3.3.0-windows-x64
  - ./blender.exe --background

################ CONTINUE HERE TOMORROW ################

