# only the blender internal python interpreter is required
language: python
​
dist: bionic

# safelist
branches:
  only:
  - main

python:
  - "3.10"

before_install:
  # update apt-gets repository sources
  - sudo apt-get update -qq

  # install blender from official sources.
  # This will most propably install an outdated blender version,
  # but it will resolve all system dependencies blender has to be able to run.
  - sudo apt-get install blender

install:
  # create temp directory where we store a recent blender version
  - mkdir tmp && cd tmp

  # download the blender version you want to test against
  - wget http://mirror.cs.umn.edu/blender.org/release/Blender3.3/blender-3.3.0-linux-x64.tar.xz

  # Extract the archive
  - tar -xJf blender-3.3.0-linux-x64.tar.xz

  # rename the extracted folder to "blender" for easier reference
  - mv blender-3.3.0-linux-x64 blender

  # remove the archive, we do not need it anymore
  - rm blender-3.3.0-linux-x64.tar.xz

  # go back to root directory
  - cd ..

################ CONTINUE HERE TOMORROW ################

