# only the blender internal python interpreter is required
language: shell

os: windows

# safelist
branches:
  only:
  - main

install:
  # create temp directory where we store a recent blender version
  - mkdir tmp
  - cd tmp

  # download the blender version you want to test against
  - wget https://download.blender.org/release/Blender3.3/blender-3.3.0-windows-x64.zip --no-check-certificate

  # Extract the archive
  - 7z x blender-3.3.0-windows-x64.zip -ao

  # test launch blender (background)
  - cd blender-3.3.0-windows-x64
  - ./blender.exe --background

################ CONTINUE HERE TOMORROW ################

